version: '3.9'

services:
  api:
    build: .
    container_name: "genai_app"
    ports:
      - "8080:8000"
    command: uvicorn main:app --reload --host=0.0.0.0
    volumes:
      - .:/workspace
    networks:
      - my_network

networks:
  my_network:
    external: true